spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/galeria
    username: postgres
    password: postgres
  spa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true

